version: "3"
services:
  grid-ui:
    container_name: grid-ui
    build:
      context: app/grid-ui
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
      - 80
    ports:
      - 80:80

  flask-app:
    container_name: flask-app
    build:
      context: app/flask-app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    expose:
    - 5000
    ports:
    - 5000:5000
