version: "3"
services:
  grid-ui:
    container_name: grid-ui
    build:
      context: app/grid-ui
      dockerfile: Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000

  flask-app:
    container_name: flask-app
    build:
      context: app/flask-app
      dockerfile: Dockerfile
    expose:
    - 5000
    ports:
    - 5000:5000
