app:
  language: english
  level: 0
  problem_grid: resources/problem-grids/L2_P3.json
  results: temp/results.json
levels:
  0.1:
    file: resources/problem-grids/shortest_path.json
    name: Shortest Path
  0.2:
    file: resources/problem-grids/go_home.json
    name: Go Home
